[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd client && npm install"]

[phases.build]
cmds = [
  "cd client && vite build"
]

[start]
# Use sirv for production-ready static file serving with SPA support
cmd = """
cd client && \
npm install -g sirv-cli && \
sirv dist --single --host 0.0.0.0 --port $PORT
"""