[phases.setup]
nixPkgs = ["nodejs", "postgresql"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build",
  "esbuild server/index.ts --platform=node --packages=external --bundle --format=cjs --outdir=dist",
  "chmod +x dist/index.js"
]

[start]
cmd = "NODE_ENV=production node dist/index.js"