[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "esbuild server/index.ts --platform=node --packages=external --bundle --format=cjs --outfile=dist/index.js"
]

[start]
cmd = "NODE_ENV=production node dist/index.js"