[phases.setup]
nixPkgs = ["nodejs", "postgresql"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build",
  "mkdir -p server/public",
  "cp -r dist/* server/public/"
]

[start]
cmd = "NODE_ENV=production npm run start"